# -*- coding: utf-8 -*-
"""ParaModPlot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aQTbiMM95vGLVMs6X2W8lbOAPkjpYWiO
"""

import numpy as np
import matplotlib.pyplot as plt

# Data
support_levels = [1, 2, 3]
gsp_counts = [182, 448, 741]
mfs_counts = [182, 405, 601]

plt.figure(figsize=(10, 6))
plt.plot(support_levels, gsp_counts, label='GSP', marker='o', color='blue')
plt.plot(support_levels, mfs_counts, label='MFS', marker='o', color='green')

# Adding titles and labels
plt.title('Pattern Counts by MaxGap for GSP and MFS Algorithms')
plt.xlabel('Max Gap')
plt.ylabel('Number of Patterns Found')
plt.xticks(support_levels)
plt.grid(True)
plt.legend()

# Show the plot
plt.show()
